update githubaction cloudformation

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,59 +1,87 @@
-name: ecr push image
+name: ECR Push Image with Commit Message
 
 on:
   push:
-    tags:
-      - v*  # 'v' で始まるタグに反応（例: v1.0.0）
+    branches:
+      - 'main'
+#    tags:
+#      - v*  # 'v' で始まるタグに反応（例: v1.0.0）
 
 jobs:
-  push:
+  extract-commit-message:
     runs-on: ubuntu-latest
-    # `permissions` を設定しないと OIDC が使えないので注意
+    outputs:
+      repository-name: ${{ steps.extract-repo-name.outputs.repository-name }}
+    steps:
+      - uses: actions/checkout@v3
+      - id: extract-repo-name
+        run: |
+          commit_message=$(git log -1 --pretty=%B)
+          echo "Commit message: $commit_message"
+          repository_name=$(echo "$commit_message" | grep -oP '(?<=<).*(?=>)' || true)
+          if [[ -z "$repository_name" ]]; then
+            echo "Repository name not found in commit message"
+            echo "::set-output name=repository-name::"
+          else
+            echo "::set-output name=repository-name::${repository_name}"
+          fi
+
+  push:
+    if: ${{ needs.extract-commit-message.outputs.repository-name != ''}}
+    runs-on: ubuntu-latest
+    needs: extract-commit-message
+    outputs:
+      repository-name: ${{ steps.build-push.outputs.repository-name }}
     permissions:
       id-token: write
       contents: read
-    # github actionを止める／再開する場合は削除
-    if: false
     steps:
-      - name: Checkout code
       - uses: actions/checkout@v3
 
       # AWS 認証
-      - uses: aws-actions/configure-aws-credentials@v1
+      - uses: aws-actions/configure-aws-credentials@v1-node16
         with:
-          aws-region: ap-northeast-1
-          role-to-assume: arn:aws:iam::747280103911:user/tenten
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
           role-session-name: GitHubActions
 
       # ECR ログイン
       - uses: aws-actions/amazon-ecr-login@v1
-        id: login-ecr
-        with:
-          mask-password: false
-          registry-type: private
-          skip-logout: false
-
 
       # Docker イメージを build・push する
-      - name: build and push docker image to ecr
-        env:
-          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-          AWS_REGION: ${{ secrets.AWS_REGION }}
-          IMAGE_TAG: ${{ github.sha }}
+      - name: Build and push Docker image
+        id: build-push
         run: |
-          REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
-          REPOSITORY_NAME=$(basename ${{ github.repository }})
-          IMAGE_NAME="${REGISTRY}/${REPOSITORY_NAME}:${IMAGE_TAG}"
-          docker build -t ${IMAGE_NAME} . -f docker/Dockerfile
-          docker push ${IMAGE_NAME}
+          REPOSITORY_NAME=${{ needs.extract-commit-message.outputs.repository-name }}
+          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${REPOSITORY_NAME}:${{ github.sha }}"
+          docker build -t ${IMAGE_URI} ./${REPOSITORY_NAME} -f ${REPOSITORY_NAME}/docker/Dockerfile
+          docker push ${IMAGE_URI}
           
-          IMAGE_URI="747280103911.dkr.ecr.ap-northeast-1.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}"
-          # 関数の存在確認
-          if aws lambda get-function --function-name ${REPOSITORY_NAME} --region ap-northeast-1 --no-cli-pager ; then
-              # 関数が存在する場合、更新
-              aws lambda update-function-code --function-name ${REPOSITORY_NAME} --image-uri ${IMAGE_URI} --region ap-northeast-1 --no-cli-pager
-          else
-              # 関数が存在しない場合、新規作成
-              # ここでは追加の必要なオプション（ロール、ランタイムなど）を指定する必要があります
-              aws lambda create-function --function-name $FUNCTION_NAME --code ImageUri=${IMAGE_URI} --region ${AWS_REGION} --no-cli-pager
-          fi
+          echo "::set-output name=repository-name::${REPOSITORY_NAME}"
+
+  deploy:
+    if: ${{ needs.push.outputs.repository-name != ''}}
+    runs-on: ubuntu-latest
+    needs: push
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v3
+
+      # AWS 認証
+      - uses: aws-actions/configure-aws-credentials@v1-node16
+        with:
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          role-session-name: GitHubActions
+
+      - name: Deploy to CloudFormation
+        run: |
+          REPOSITORY_NAME=${{ needs.push.outputs.repository-name }}
+          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${REPOSITORY_NAME}:${{ github.sha }}"
+          aws cloudformation deploy \
+            --template-file ${REPOSITORY_NAME}/cloudformation/cloudformation-template.yaml \
+            --stack-name ${REPOSITORY_NAME} \
+            --parameter-overrides ImageUri=${IMAGE_URI} FunctionName=${REPOSITORY_NAME} \
+            --capabilities CAPABILITY_IAM
